filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      hints.default_config:
        type: container
        paths:
          - /var/lib/docker/containers/${data.container.id}/*.log

processors:
  - add_docker_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]

setup.template.enabled: false
setup.ilm.enabled: false
logging.to_files: false